### ISSUE TITLE
New release with parquet-tools 1.10.1?

### ISSUE THREAD

**Issue by panthony** [spotify/gcs-tools#11]
Hello there 👋 

I noticed that you updated the version of `parquet-tools` on master (allowing usage of `rowcount` 🙏 ) for a fair amount of time now but there was no release with it.

Do you have any idea if/when you would be able to make a new release?

Relying heavily on parquet hosted on GCS, this is cruelly missing!

Nonetheless, thanks for this awesome tool 👍

**Comment by regadas** [comment]
Hi @panthony, I'll see if i can do a release tmr after having a look at #12.
