### ISSUE TITLE
error running proto-tools tojson

### ISSUE THREAD

**Issue by chris-gomes** [spotify/gcs-tools#16]
running `proto-tools tojson` throws this error:
> Exception in thread "main" java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.newInstance(Ljava/nio/ByteBuffer;)Lcom/google/protobuf/CodedInputStream;
>	at me.lyh.protobuf.generic.GenericReader.read(GenericReader.scala:21)
>	at org.apache.avro.tool.ProtobufReader.toJson(ProtobufReader.scala:9)
>	at org.apache.avro.tool.ProtoToJsonTool.run(ProtoToJsonTool.java:59)
>	at org.apache.avro.tool.ProtoMain.run(ProtoMain.java:64)
>	at org.apache.avro.tool.ProtoMain.main(ProtoMain.java:53)`

**Comment by nevillelyh** [comment]
So `avro-tools` jar includes old protobuf class files too. :facepalm:
Fixed in e61d66f

**Comment by nevillelyh** [comment]
https://github.com/spotify/homebrew-public/pull/64
Updated homebrew also.
