### ISSUE TITLE
avro-tools tojson, get part of...

### ISSUE THREAD

**Issue by klappenbach** [spotify/gcs-tools#17]
Wondering if we could update avro-tools so we can do `avro-tools tojson --head=10 <avrofile>`? :slightly_smiling_face:
Currently missing this, which seems to [be a part of later version](https://github.com/apache/avro/pull/100) of apache avro.

**Comment by nevillelyh** [comment]
Done
https://github.com/spotify/gcs-tools/releases/tag/v0.1.12
https://github.com/spotify/homebrew-public/pull/70
